{% set name = "pytest-ignore-flaky" %}
{% set version = "1.0.0" %}
{% set sha256 = "29b3099cf4d424fd553d39940f7025acf6847ecbba292649a0dc764dfbb7d59e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pytest >=2.7

test:
  imports:
    - pytest_ignore_flaky

about:
  home: https://github.com/schettino72/pytest-ignore-flaky
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'ignore failures from flaky tests (pytest plugin)'
  dev_url: https://github.com/schettino72/pytest-ignore-flaky


extra:
  recipe-maintainers:
    - rmcgibbo
