travis:
  secure:
    BINSTAR_TOKEN: rByAvkk2L0ELdqtClD2d8U1W1LUqrl7uxoy60gAW+XnUjdwJeKolFSAqXYYATUdcQBbEnuO7EIdTTW0HIsAguNF8/3sYzT5ig/KvKoNGqo+RbCZ/lKUalO0vQ3OwMIaeknEsR8Wpb3vzNim0LnEL9P0P9UZyLWCYkArjV4HvhATdrnet3jM7CA8Ufi59W0JIsWN2ePS1GeRkGw9Lu9jvoMKT6ZbOGy/L0siY4RBxP7C8G77YOdDg22T3mnl3r631oJHGmwkw8eTHzhPD+Lg1xpC7TUrnzR0hcRr6B3s8vURH2o7Ch+7mL/Gq8ww3h0T70lf+h03XPvXflN3jDk1LyOourGDj/H9TOxdwa+sUYC8aSzlwLyZN0i9768fc4Htk63pENbyzHCruTr1F8w8hQ4Duh3HZbTp3YlYdF5LM+vQimFwLlKiTDr475kXNgBWX9t1FQuFisghx5cIhYvzJLYScHM1YTyEz2mljoeoM8SBrc3x7vvv/KbRm6oTfWhgIJPsuNbQPzAwh36GDrUTA64bNdU6Q3lKysgFqP4odGdpqisq6TNOQERNFxdORTSGvuvcA7Kuuffqu5p4QZupxezinJ9SqvyujKdS4g89Y9T3g6rlcnDBfd4QsYienWc6Du7aRAtmJN0CJG1Jmd+GH8YuorwcCOwGaoOuvSlfqfHw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
